# Generated by Django 5.1.2 on 2024-10-10 12:39

from django.db import migrations, models

import artquery.general.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    'password',
                    models.CharField(max_length=128, verbose_name='password')
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    )
                ),
                (
                    'account_number',
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            artquery.general.validators.HexStringValidator(64)
                        ]
                    )
                ),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('display_image', models.URLField(blank=True)),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
